import Head from "next/head";
import { getPosts } from "@/lib/ghost";
import { PostOrPage } from "@tryghost/content-api";
import Link from "next/link";

export async function getStaticProps() {
  const posts = await getPosts();
  return {
    props: { posts },
  };
}

export default function Home({ posts }: { posts: PostOrPage[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-xl p-4">
        {posts?.map((post) => (
          <div key={post.id} className="mb-4">
            <Link href={`/${post.slug}`}>
              <h3 className="text-xl">{post.title}</h3>
            </Link>
            <p className="text-slate-700 text-sm">{post.excerpt}</p>
          </div>
        ))}
      </main>
    </>
  );
}
